"use client";
import { useState } from "react";
import Link from "next/link";

export default function ResetPassword() {
  const [phone, setPhone] = useState(""); const [code, setCode] = useState(""); const [password, setPassword] = useState(""); const [sent, setSent] = useState(false); const [devCode, setDevCode] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function requestCode(e) { e.preventDefault(); setError(""); setBusy(true); try { const r = await fetch("/api/customer/password-reset/request", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ phone }) }); const d = await r.json(); if (!r.ok) { setError(d.error || "Unable to request reset."); return; } setSent(true); if (d.devCode) setDevCode(d.devCode); } catch { setError("Unable to connect to the server."); } finally { setBusy(false); } }
  async function confirm(e) { e.preventDefault(); setError(""); setBusy(true); try { const r = await fetch("/api/customer/password-reset/confirm", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ phone, code, password }) }); const d = await r.json(); if (!r.ok) { setError(d.error || "Unable to reset password."); return; } window.location.href = "/customer/profile"; } catch { setError("Unable to connect to the server."); } finally { setBusy(false); } }
  return <main className="min-h-screen bg-[#f7f8f4] p-4 flex items-center justify-center"><form onSubmit={sent ? confirm : requestCode} className="w-full max-w-md bg-white rounded-3xl p-6 shadow-sm border border-gray-200 space-y-4"><div><h1 className="text-2xl font-black">Reset password</h1><p className="text-gray-500 mt-1">We use your phone number to verify the reset.</p></div>{error && <div className="rounded-xl bg-red-50 text-red-700 p-3">{error}</div>}{!sent ? <><input required value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="Phone number" className="w-full rounded-xl border p-3" inputMode="tel" /><button disabled={busy} className="w-full rounded-xl bg-black text-white p-3 font-bold">{busy ? "Sending…" : "Send code"}</button></> : <><input required maxLength={6} value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))} placeholder="6-digit code" className="w-full rounded-xl border p-3" inputMode="numeric" />{devCode && <div className="rounded-xl bg-yellow-50 text-yellow-800 p-3 text-sm">Development code: <b>{devCode}</b></div>}<input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="New password (8+ characters)" className="w-full rounded-xl border p-3" /><button disabled={busy} className="w-full rounded-xl bg-black text-white p-3 font-bold">{busy ? "Resetting…" : "Reset password"}</button></>}<p className="text-sm text-center"><Link className="underline" href="/customer/login">Back to login</Link></p></form></main>;
}